### PR TITLE
Feature/ticket01

### PR DESCRIPTION
**Pull request by lvaldenebro**
Changes the way toggle is done in forms. The code is being rewritten and simplified.

### CODE REVIEW

**Comment by anabollain** [comment]
Really nice job using a loop combined with switch to optimize the code. Thanks for your work Laura & Marta! :)

**Comment by celiamartin11** [comment]
Thank you very much for your work Laura and Marta, I'm friking out! ;)

**Comment by lvaldenebro** [comment]
> Really nice job using a loop combined with switch to optimize the code. Thanks for your work Laura & Marta! :)

Thank you, Ana! If you think the code deserves it, could you please approve changes, so we can merge them? Thanks!

**Comment by lvaldenebro** [comment]
> Thank you very much for your work Laura and Marta, I'm friking out! ;)

Thank you, Celia! :D If you think the code deserves it, could you please approve changes, so we can merge them? Thanks!

**Pull request merged**
